Repository MomentOurs/MomentOurs, pull requests merged in 2025-02, with the labels that each got.

#76 feat(#75 ): 데이트 코스 즐겨찾기 등록, 삭제, 조회 기능 추가
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/course_scrap/command/application/controller/CourseScrapController.java
  src/main/java/beyond/momentours/course_scrap/command/application/dto/CourseScrapDTO.java
  src/main/java/beyond/momentours/course_scrap/command/application/mapper/CourseScrapConverter.java
  src/main/java/beyond/momentours/course_scrap/command/application/service/CourseScrapService.java
  src/main/java/beyond/momentours/course_scrap/command/application/service/CourseScrapServiceImpl.java
  src/main/java/beyond/momentours/course_scrap/command/domain/repository/CourseScrapRepository.java
  src/main/java/beyond/momentours/course_scrap/command/domain/vo/CourseScrapVO.java
  src/main/java/beyond/momentours/course_scrap/command/domain/vo/request/RequestCreateCourseScrapVO.java
  src/main/java/beyond/momentours/course_scrap/command/domain/vo/response/ResponseCreateCourseScrapVO.java
  src/main/java/beyond/momentours/course_scrap/query/repository/CourseScrapMapper.java
  src/main/resources/beyond/momentours/mapper/course_scrap/CourseScrapMapper.xml
Labels: feat✨, BackEnd🔙

#79 feat(#78 ): 신고 등록 기능
  src/main/java/beyond/momentours/report/command/application/controller/ReportController.java
  src/main/java/beyond/momentours/report/command/application/dto/ReportDTO.java
  src/main/java/beyond/momentours/report/command/application/mapper/ReportConverter.java
  src/main/java/beyond/momentours/report/command/application/service/ReportService.java
  src/main/java/beyond/momentours/report/command/application/service/ReportServiceImpl.java
  src/main/java/beyond/momentours/report/command/domain/aggregate/ProcessStatus.java
  src/main/java/beyond/momentours/report/command/domain/aggregate/ReportReason.java
  src/main/java/beyond/momentours/report/command/domain/aggregate/ReportType.java
  src/main/java/beyond/momentours/report/command/domain/aggregate/entity/Report.java
  src/main/java/beyond/momentours/report/command/domain/repository/ReportRepository.java
  src/main/java/beyond/momentours/report/command/domain/vo/request/RequestCreateReportVO.java
  src/main/java/beyond/momentours/report/command/domain/vo/response/ResponseCreateReportVO.java
  src/main/java/beyond/momentours/report/query/repository/ReportMapper.java
  src/main/resources/beyond/momentours/mapper/report/ReportMapper.xml
Labels: feat✨, BackEnd🔙

#82 feat(#81 ): 신고 조회 기능 추가
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/pre_blacklist/command/application/dto/PreBlackListDTO.java
  src/main/java/beyond/momentours/pre_blacklist/command/application/service/PreBlackListService.java
  src/main/java/beyond/momentours/pre_blacklist/command/application/service/PreBlackListServiceImpl.java
  src/main/java/beyond/momentours/pre_blacklist/command/domain/aggregate/entity/PreBlackList.java
  src/main/java/beyond/momentours/pre_blacklist/command/domain/repository/PreBlackListRepository.java
  src/main/java/beyond/momentours/pre_blacklist/query/controller/PreBlackListQueryController.java
  src/main/java/beyond/momentours/pre_blacklist/query/dto/PreBlackListDTO.java
  src/main/java/beyond/momentours/pre_blacklist/query/repository/PreBlackListMapper.java
  src/main/java/beyond/momentours/pre_blacklist/query/service/PreBlackListQueryService.java
  src/main/java/beyond/momentours/pre_blacklist/query/service/PreBlackListQueryServiceImpl.java
  src/main/java/beyond/momentours/pre_blacklist/query/vo/response/ResponsePreBlackListAll.java
  src/main/java/beyond/momentours/report/command/application/controller/ReportCommandController.java
  src/main/java/beyond/momentours/report/command/application/dto/ReportDTO.java
  src/main/java/beyond/momentours/report/command/application/service/ReportCommandService.java
  src/main/java/beyond/momentours/report/command/application/service/ReportCommandServiceImpl.java
  src/main/java/beyond/momentours/report/command/domain/aggregate/entity/Report.java
  src/main/java/beyond/momentours/report/query/controller/ReportQueryController.java
  src/main/java/beyond/momentours/report/query/repository/ReportMapper.java
  src/main/java/beyond/momentours/report/query/service/ReportQueryService.java
  src/main/java/beyond/momentours/report/query/service/ReportQueryServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/beyond/momentours/mapper/pre_blacklist/PreBlackListMapper.xml
  src/main/resources/beyond/momentours/mapper/report/ReportMapper.xml
Labels: feat✨, BackEnd🔙

#83 ResultMapper 수정 + Config 관련 수정
  src/main/java/beyond/momentours/announcement/query/config/MyBatisConfiguration.java
  src/main/java/beyond/momentours/couple/query/config/MybatisConfiguration.java
  src/main/resources/beyond/momentours/mapper/report/ReportMapper.xml
Labels: BackEnd🔙, fix🛠️

#88 feat(#87): 회원 관련 부가 기능 구현
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/member/command/application/controller/MemberController.java
  src/main/java/beyond/momentours/member/command/application/service/MemberService.java
  src/main/java/beyond/momentours/member/command/application/service/MemberServiceImpl.java
  src/main/java/beyond/momentours/member/command/domain/aggregate/entity/Member.java
  src/main/java/beyond/momentours/member/query/controller/AdminController.java
  src/main/java/beyond/momentours/member/query/controller/MemberController.java
  src/main/java/beyond/momentours/member/query/dto/LoginHistoryDTO.java
  src/main/java/beyond/momentours/member/query/repository/AdminMapper.java
  src/main/java/beyond/momentours/member/query/repository/MemberMapper.java
  src/main/java/beyond/momentours/member/query/service/AdminQueryService.java
  src/main/java/beyond/momentours/member/query/service/AdminQueryServiceImpl.java
  src/main/java/beyond/momentours/member/query/service/MemberQueryService.java
  src/main/java/beyond/momentours/member/query/service/MemberQueryServiceImpl.java
  src/main/java/beyond/momentours/member/query/vo/response/ResponseLoginHistoryVO.java
  src/main/java/beyond/momentours/member/query/vo/response/ResponseMemberSearchVO.java
  src/main/java/beyond/momentours/security/JWTFilter.java
  src/main/java/beyond/momentours/security/JwtAuthenticationProvider.java
  src/main/java/beyond/momentours/security/SecurityConfig.java
  src/main/java/beyond/momentours/util/SecurityUtil.java
  src/main/resources/beyond/momentours/mapper/member/AdminMapper.xml
  src/main/resources/beyond/momentours/mapper/member/MemberMapper.xml
Labels: feat✨, BackEnd🔙

#89 feat(#39): 댓글 조회 기능 추가 및 CQRS 패턴 적용을 위해 수정
  src/main/java/beyond/momentours/comment/command/application/controller/CommentCommandController.java
  src/main/java/beyond/momentours/comment/command/application/dto/CommentDTO.java
  src/main/java/beyond/momentours/comment/command/application/mapper/CommentConverter.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentCommandService.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentCommandServiceImpl.java
  src/main/java/beyond/momentours/comment/command/domain/aggregate/CommentType.java
  src/main/java/beyond/momentours/comment/command/domain/aggregate/entity/Comment.java
  src/main/java/beyond/momentours/comment/command/domain/vo/request/RequestCreateCommentVO.java
  src/main/java/beyond/momentours/comment/command/domain/vo/response/ResponseCreateCommentVO.java
  src/main/java/beyond/momentours/comment/query/controller/CommentQueryController.java
  src/main/java/beyond/momentours/comment/query/repository/CommentMapper.java
  src/main/java/beyond/momentours/comment/query/service/CommentQueryService.java
  src/main/java/beyond/momentours/comment/query/service/CommentQueryServiceImpl.java
  src/main/java/beyond/momentours/date_course/command/application/controller/DateCourseCommandController.java
  src/main/java/beyond/momentours/date_course/command/application/dto/DateCourseDTO.java
  src/main/java/beyond/momentours/date_course/command/application/mapper/DateCourseConverter.java
  src/main/java/beyond/momentours/date_course/command/application/service/DateCourseCommandService.java
  src/main/java/beyond/momentours/date_course/command/application/service/DateCourseCommandServiceImpl.java
  src/main/java/beyond/momentours/date_course/command/domain/aggregate/entity/DateCourse.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/request/RequestCreateDateCourseVO.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/request/RequestUpdateDateCourseVO.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/response/ResponseCreateDateCourseVO.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/response/ResponseDateCourseDetailVO.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/response/ResponseDateCourseListVO.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/response/ResponseUpdateDateCourseVO.java
  src/main/java/beyond/momentours/date_course/query/controller/DateCourseQueryController.java
  src/main/java/beyond/momentours/date_course/query/service/DateCourseQueryService.java
  src/main/java/beyond/momentours/date_course/query/service/DateCourseQueryServiceImpl.java
  src/main/java/beyond/momentours/date_course_location/command/application/service/DateCourseLocationServiceImpl.java
  src/main/java/beyond/momentours/date_course_location/command/domain/aggregate/entity/DateCourseLocation.java
  src/main/java/beyond/momentours/date_course_location/command/domain/vo/DateCourseLocationVO.java
  src/main/java/beyond/momentours/randomquestion/query/repository/RandomQuestionMapper.java
  src/main/resources/beyond/momentours/mapper/comment/CommentMapper.xml
  src/main/resources/beyond/momentours/mapper/date_course/DateCourseMapper.xml
  src/main/resources/beyond/momentours/mapper/randomquestion/RandomQuestionMapper.xml
Labels: feat✨, BackEnd🔙, fix🛠️

#91 feat(#90): 데이트 코스에서 추억을 통해 증명하는 것 + 일정 등록하는 기능 추가
  src/main/java/beyond/momentours/date_course/command/application/controller/DateCourseCommandController.java
  src/main/java/beyond/momentours/date_course/command/application/mapper/DateCourseConverter.java
  src/main/java/beyond/momentours/date_course/command/application/service/DateCourseCommandService.java
  src/main/java/beyond/momentours/date_course/command/application/service/DateCourseCommandServiceImpl.java
  src/main/java/beyond/momentours/date_course/command/domain/aggregate/entity/DateCourse.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/request/RequestCreateDateCourseVO.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/request/RequestUpdateDateCourseScheduleVO.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/request/RequestUpdateDateCourseVO.java
  src/main/java/beyond/momentours/date_course_location/command/application/service/DateCourseLocationCommandService.java
  src/main/java/beyond/momentours/date_course_location/command/application/service/DateCourseLocationCommandServiceImpl.java
  src/main/java/beyond/momentours/date_course_location/query/repository/DateCourseLocationMapper.java
  src/main/java/beyond/momentours/date_course_location/query/service/DateCourseLocationQueryService.java
  src/main/java/beyond/momentours/date_course_location/query/service/DateCourseLocationQueryServiceImpl.java
  src/main/java/beyond/momentours/plan/command/application/controller/PlanCommandController.java
  src/main/java/beyond/momentours/plan/command/application/dto/PlanDTO.java
  src/main/java/beyond/momentours/plan/command/application/mapper/PlanConverter.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanCommandService.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanCommandServiceImpl.java
  src/main/java/beyond/momentours/plan/command/domain/aggregate/PlanType.java
  src/main/java/beyond/momentours/plan/command/domain/aggregate/entity/Plan.java
  src/main/java/beyond/momentours/plan/command/domain/vo/request/RequestCreatePlanVO.java
  src/main/java/beyond/momentours/plan/command/domain/vo/request/RequestUpdatePlanVO.java
  src/main/java/beyond/momentours/plan/command/domain/vo/response/ResponseCreatePlanVO.java
  src/main/java/beyond/momentours/plan/command/domain/vo/response/ResponseUpdatePlanVO.java
  src/main/java/beyond/momentours/plan/query/controller/controller/PlanQueryController.java
  src/main/java/beyond/momentours/plan/query/repository/PlanMapper.java
  src/main/java/beyond/momentours/plan/query/service/PlanQueryService.java
  src/main/java/beyond/momentours/plan/query/service/PlanQueryServiceImpl.java
  src/main/resources/beyond/momentours/mapper/date_course_location/DateCourseLocationMapper.xml
  src/main/resources/beyond/momentours/mapper/plan/PlanMapper.xml
Labels: feat✨, BackEnd🔙
