Repository MomentOurs/MomentOurs, pull requests merged in 2025-01, with the labels that each got.

#6 Feat: 추억 도메인 개발구조 세팅 및 에러코드 추가
  src/main/java/beyond/momentours/common/ResponseDTO.java
  src/main/java/beyond/momentours/common/exception/CommonException.java
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/common/exception/ExceptionDTO.java
  src/main/java/beyond/momentours/common/exception/GlobalExceptionHandler.java
  src/main/java/beyond/momentours/moment/command/application/controller/MomentController.java
  src/main/java/beyond/momentours/moment/command/application/service/MomentService.java
  src/main/java/beyond/momentours/moment/command/application/service/MomentServiceImpl.java
  src/main/java/beyond/momentours/moment/command/domain/aggregate/entity/Moment.java
  src/main/java/beyond/momentours/moment/query/config/MybatisConfiguration.java
Labels: feat✨

#7 feat: 추억 등록 api 개발
  build.gradle
  src/main/java/beyond/momentours/config/AppConfiguration.java
  src/main/java/beyond/momentours/location/command/application/controller/LocationController.java
  src/main/java/beyond/momentours/location/command/application/dto/RequestLocationDTO.java
  src/main/java/beyond/momentours/location/command/application/dto/ResponseLocationDTO.java
  src/main/java/beyond/momentours/location/command/application/service/LocationService.java
  src/main/java/beyond/momentours/location/command/domain/aggregate/entity/Location.java
  src/main/java/beyond/momentours/location/command/domain/repository/LocationRepository.java
  src/main/java/beyond/momentours/moment/command/application/controller/MomentController.java
  src/main/java/beyond/momentours/moment/command/application/dto/RequestMomentDTO.java
  src/main/java/beyond/momentours/moment/command/application/dto/ResponseMomentDTO.java
  src/main/java/beyond/momentours/moment/command/application/service/MomentService.java
  src/main/java/beyond/momentours/moment/command/application/service/MomentServiceImpl.java
  src/main/java/beyond/momentours/moment/command/domain/repository/MomentRepository.java
  src/main/resources/application.yml
Labels: feat✨

#10 feat(#9): 일정 도메인 추가, 등록 기능 추가
  src/main/java/beyond/momentours/plan/command/application/controller/PlanController.java
  src/main/java/beyond/momentours/plan/command/application/dto/PlanDTO.java
  src/main/java/beyond/momentours/plan/command/application/mapper/PlanConverter.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanService.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanServiceImpl.java
  src/main/java/beyond/momentours/plan/command/domain/aggregate/entity/Plan.java
  src/main/java/beyond/momentours/plan/command/domain/repository/PlanRepository.java
  src/main/java/beyond/momentours/plan/command/domain/vo/request/RequestRegisterPlanVO.java
  src/main/java/beyond/momentours/plan/command/domain/vo/response/ResponseRegisterPlanVO.java
  src/main/java/beyond/momentours/plan/query/repository/PlanMapper.java
  src/main/resources/beyond/momentours/mapper/PlanMapper.xml
Labels: feat✨, BackEnd🔙

#16 feat(#15): .env 파일 추가
  .env
  .gitignore
  build.gradle
  src/main/resources/application.yml
Labels: feat✨, BackEnd🔙

#17 feat, fix(#13 ): 일정 삭제 기능 추가, MyBatisConfiguration 클래스 위치 이동
  src/main/java/beyond/momentours/config/MybatisConfiguration.java
  src/main/java/beyond/momentours/moment/query/config/MybatisConfiguration.java
  src/main/java/beyond/momentours/moment/query/repository/MomentMapper.java
  src/main/java/beyond/momentours/plan/command/application/controller/PlanController.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanService.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanServiceImpl.java
  src/main/java/beyond/momentours/plan/command/domain/aggregate/entity/Plan.java
Labels: feat✨, BackEnd🔙, fix🛠️

#20 feat(#19 ): 커플 일정 월별 조회 기능 추가
  src/main/java/beyond/momentours/plan/command/application/controller/PlanController.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanService.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanServiceImpl.java
  src/main/java/beyond/momentours/plan/query/repository/PlanMapper.java
  src/main/resources/beyond/momentours/mapper/PlanMapper.xml
Labels: feat✨, BackEnd🔙

#25 feat(#23 , #24 ): 특정 날짜에 속하는 일정(들) 조회, 특정 일정 조회 기능 추가
  .env
  src/main/java/beyond/momentours/plan/command/application/controller/PlanController.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanService.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanServiceImpl.java
  src/main/java/beyond/momentours/plan/query/repository/PlanMapper.java
  src/main/resources/beyond/momentours/mapper/PlanMapper.xml
Labels: feat✨, BackEnd🔙, fix🛠️

#29 fix: 일정 쪽 메서드명, url 변경
  src/main/java/beyond/momentours/plan/command/application/controller/PlanController.java
  src/main/java/beyond/momentours/plan/command/application/mapper/PlanConverter.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanService.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanServiceImpl.java
  src/main/java/beyond/momentours/plan/command/domain/aggregate/entity/Plan.java
  src/main/java/beyond/momentours/plan/command/domain/vo/request/RequestCreatePlanVO.java
  src/main/java/beyond/momentours/plan/command/domain/vo/request/RequestUpdatePlanVO.java
  src/main/java/beyond/momentours/plan/command/domain/vo/response/ResponseCreatePlanVO.java
Labels: fix🛠️

#28 feat(#27 ): 댓글 엔터티 추가, 댓글 등록 기능 추가
  src/main/java/beyond/momentours/comment/command/application/controller/CommentController.java
  src/main/java/beyond/momentours/comment/command/application/dto/CommentDTO.java
  src/main/java/beyond/momentours/comment/command/application/mapper/CommentConverter.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentService.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentServiceImpl.java
  src/main/java/beyond/momentours/comment/command/domain/aggregate/CommentType.java
  src/main/java/beyond/momentours/comment/command/domain/aggregate/entity/Comment.java
  src/main/java/beyond/momentours/comment/command/domain/repository/CommentRepository.java
  src/main/java/beyond/momentours/comment/command/domain/vo/request/RequestCreateCommentVO.java
  src/main/java/beyond/momentours/comment/command/domain/vo/response/ResponseCreateCommentVO.java
  src/main/java/beyond/momentours/comment/query/repository/CommentMapper.java
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/resources/beyond/momentours/mapper/CommentMapper.xml
Labels: feat✨, BackEnd🔙

#30 feat(#28): 커플 생성, 인증 및 프로필 사진 수정 메서드 구현
  build.gradle
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/config/RedisConfig.java
  src/main/java/beyond/momentours/config/SwaggerConfiguration.java
  src/main/java/beyond/momentours/couple/command/application/controller/CommandCoupleController.java
  src/main/java/beyond/momentours/couple/command/application/dto/CoupleListDTO.java
  src/main/java/beyond/momentours/couple/command/application/dto/CoupleProfileDTO.java
  src/main/java/beyond/momentours/couple/command/application/dto/MatchingCodeDTO.java
  src/main/java/beyond/momentours/couple/command/application/service/CommandCoupleService.java
  src/main/java/beyond/momentours/couple/command/application/service/CommandCoupleServiceImpl.java
  src/main/java/beyond/momentours/couple/command/application/service/CoupleMatchingService.java
  src/main/java/beyond/momentours/couple/command/application/service/CoupleMatchingServiceImpl.java
  src/main/java/beyond/momentours/couple/command/domain/aggregate/entity/CoupleList.java
  src/main/java/beyond/momentours/couple/command/domain/aggregate/entity/CoupleMatchingStatus.java
  src/main/java/beyond/momentours/couple/command/domain/aggregate/entity/MatchingCode.java
  src/main/java/beyond/momentours/couple/command/domain/aggregate/entity/MatchingStatus.java
  src/main/java/beyond/momentours/couple/command/domain/repository/CoupleRepository.java
  src/main/java/beyond/momentours/couple/command/domain/vo/CoupleListVO.java
  src/main/java/beyond/momentours/couple/command/domain/vo/CoupleProfileRequestVO.java
  src/main/java/beyond/momentours/couple/command/domain/vo/CoupleProfileResponseVO.java
  src/main/java/beyond/momentours/couple/command/domain/vo/MatchingCodeVO.java
  src/main/java/beyond/momentours/couple/query/config/MybatisConfiguration.java
  src/main/java/beyond/momentours/couple/query/repository/CoupleMapper.java
  src/test/java/beyond/momentours/couple/command/application/service/CoupleMatchingServiceImplTests.java
Labels: feat✨, BackEnd🔙

#33 feat(#32 ): 댓글 수정 기능 추가 및 일정 수정 VO 클래스 명 변경
  src/main/java/beyond/momentours/comment/command/application/controller/CommentController.java
  src/main/java/beyond/momentours/comment/command/application/mapper/CommentConverter.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentService.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentServiceImpl.java
  src/main/java/beyond/momentours/comment/command/domain/aggregate/entity/Comment.java
  src/main/java/beyond/momentours/comment/command/domain/vo/request/RequestUpdateCommentVO.java
  src/main/java/beyond/momentours/comment/command/domain/vo/response/ResponseUpdateCommentVO.java
  src/main/java/beyond/momentours/plan/command/application/controller/PlanController.java
  src/main/java/beyond/momentours/plan/command/application/mapper/PlanConverter.java
  src/main/java/beyond/momentours/plan/command/domain/vo/response/ResponseUpdatePlanVO.java
Labels: feat✨, BackEnd🔙, fix🛠️

#31 feat(31): 커플 정보를 수정하기 위한 update method 추가
  src/main/java/beyond/momentours/couple/command/application/service/CommandCoupleServiceImpl.java
  src/main/java/beyond/momentours/couple/command/domain/aggregate/entity/CoupleList.java
Labels: BackEnd🔙, fix🛠️

#35 feat(32): 커플 삭제 기능 구현 및 converter 클래스 추가
  src/main/java/beyond/momentours/couple/command/application/controller/CommandCoupleController.java
  src/main/java/beyond/momentours/couple/command/application/mapper/CodeConverter.java
  src/main/java/beyond/momentours/couple/command/application/mapper/CoupleConverter.java
  src/main/java/beyond/momentours/couple/command/application/service/CommandCoupleService.java
  src/main/java/beyond/momentours/couple/command/application/service/CommandCoupleServiceImpl.java
  src/main/java/beyond/momentours/couple/command/application/service/CoupleMatchingServiceImpl.java
  src/main/java/beyond/momentours/couple/command/domain/aggregate/entity/CoupleList.java
  src/main/java/beyond/momentours/couple/command/domain/repository/CoupleRepository.java
  src/main/java/beyond/momentours/couple/command/domain/vo/request/CoupleProfileRequestVO.java
  src/main/java/beyond/momentours/couple/command/domain/vo/response/CoupleListResponseVO.java
  src/main/java/beyond/momentours/couple/command/domain/vo/response/CoupleProfileResponseVO.java
  src/main/java/beyond/momentours/couple/command/domain/vo/response/MatchingCodeResponseVO.java
  src/main/resources/application.yml
  src/test/java/beyond/momentours/couple/command/application/service/CommandCoupleServiceImplTests.java
Labels: feat✨, BackEnd🔙, fix🛠️

#36 feat(36): 커플 번호로 활성화된 특정 커플 조회 기능 추가 + 회원 번호로 활성화된 특정 커플 조회 기능 추가
  src/main/java/beyond/momentours/couple/query/controller/QueryCoupleController.java
  src/main/java/beyond/momentours/couple/query/repository/CoupleMapper.java
  src/main/java/beyond/momentours/couple/query/service/QueryCoupleService.java
  src/main/java/beyond/momentours/couple/query/service/QueryCoupleServiceImpl.java
  src/main/resources/beyond/momentours/mapper/CoupleMapper.xml
  src/test/java/beyond/momentours/couple/query/service/QueryCoupleServiceImplTests.java
Labels: feat✨, BackEnd🔙

#37 - 제목 : feat(#34 ): 댓글 삭제 기능 추가
  src/main/java/beyond/momentours/comment/command/application/controller/CommentController.java
  src/main/java/beyond/momentours/comment/command/application/dto/CommentDTO.java
  src/main/java/beyond/momentours/comment/command/application/mapper/CommentConverter.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentService.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentServiceImpl.java
  src/main/java/beyond/momentours/comment/command/domain/aggregate/CommentType.java
  src/main/java/beyond/momentours/comment/command/domain/aggregate/entity/Comment.java
  src/main/java/beyond/momentours/comment/command/domain/vo/request/RequestCreateCommentVO.java
  src/main/java/beyond/momentours/comment/command/domain/vo/request/RequestUpdateCommentVO.java
  src/main/java/beyond/momentours/comment/command/domain/vo/response/ResponseCreateCommentVO.java
  src/main/java/beyond/momentours/comment/command/domain/vo/response/ResponseUpdateCommentVO.java
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/plan/command/application/controller/PlanController.java
  src/main/resources/beyond/momentours/mapper/CommentMapper.xml
Labels: feat✨, BackEnd🔙

#41 feat(#40): 대댓글 엔터티 추가 및 대댓글 CRUD 추가
  src/main/java/beyond/momentours/comment/query/repository/CommentMapper.java
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/reply/command/application/controller/ReplyController.java
  src/main/java/beyond/momentours/reply/command/application/dto/ReplyDTO.java
  src/main/java/beyond/momentours/reply/command/application/mapper/ReplyConvertor.java
  src/main/java/beyond/momentours/reply/command/application/service/ReplyService.java
  src/main/java/beyond/momentours/reply/command/application/service/ReplyServiceImpl.java
  src/main/java/beyond/momentours/reply/command/domain/aggregate/entity/Reply.java
  src/main/java/beyond/momentours/reply/command/domain/repository/ReplyRepository.java
  src/main/java/beyond/momentours/reply/command/domain/vo/request/RequestCreateReplyVO.java
  src/main/java/beyond/momentours/reply/command/domain/vo/request/RequestUpdateReplyVO.java
  src/main/java/beyond/momentours/reply/command/domain/vo/response/ResponseCreateReplyVO.java
  src/main/java/beyond/momentours/reply/command/domain/vo/response/ResponseUpdateReplyVO.java
  src/main/java/beyond/momentours/reply/query/repository/ReplyMapper.java
  src/main/resources/beyond/momentours/mapper/CommentMapper.xml
  src/main/resources/beyond/momentours/mapper/reply/ReplyMapper.xml
Labels: feat✨, BackEnd🔙

#38 feat(#14, #18, #21): security 설정 및 회원가입, 로그인, 회원 ID 가져오기
  build.gradle
  gradlew.bat
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/member/command/application/controller/MemberController.java
  src/main/java/beyond/momentours/member/command/application/dto/CustomUserDetails.java
  src/main/java/beyond/momentours/member/command/application/dto/JwtTokenDTO.java
  src/main/java/beyond/momentours/member/command/application/dto/LoginDTO.java
  src/main/java/beyond/momentours/member/command/application/dto/MemberDTO.java
  src/main/java/beyond/momentours/member/command/application/mapper/MemberConverter.java
  src/main/java/beyond/momentours/member/command/application/service/MemberService.java
  src/main/java/beyond/momentours/member/command/application/service/MemberServiceImpl.java
  src/main/java/beyond/momentours/member/command/domain/aggregate/entity/Member.java
  src/main/java/beyond/momentours/member/command/domain/aggregate/entity/MemberRole.java
  src/main/java/beyond/momentours/member/command/domain/repository/MemberRepository.java
  src/main/java/beyond/momentours/member/command/domain/vo/reponse/ResponseLoginMemberVO.java
  src/main/java/beyond/momentours/member/command/domain/vo/reponse/ResponseSignupMemberVO.java
  src/main/java/beyond/momentours/member/command/domain/vo/request/RequestLoginMemberVO.java
  src/main/java/beyond/momentours/member/command/domain/vo/request/RequestSignupMemberVO.java
  src/main/java/beyond/momentours/member/query/controller/MemberController.java
  src/main/java/beyond/momentours/member/query/dto/MemberDTO.java
  src/main/java/beyond/momentours/member/query/repository/MemberMapper.java
  src/main/java/beyond/momentours/member/query/service/MemberService.java
  src/main/java/beyond/momentours/member/query/service/MemberServiceImpl.java
  src/main/java/beyond/momentours/security/AuthenticationFilter.java
  src/main/java/beyond/momentours/security/CorsMvcConfig.java
  src/main/java/beyond/momentours/security/JWTFilter.java
  src/main/java/beyond/momentours/security/JWTUtil.java
  src/main/java/beyond/momentours/security/JwtAuthenticationProvider.java
  src/main/java/beyond/momentours/security/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/beyond/momentours/mapper/comment/CommentMapper.xml
  src/main/resources/beyond/momentours/mapper/couple/CoupleMapper.xml
  src/main/resources/beyond/momentours/mapper/member/MemberMapper.xml
  src/main/resources/beyond/momentours/mapper/plan/PlanMapper.xml
Labels: feat✨, BackEnd🔙, fix🛠️

#49 feat(#48): 데이트 코스 등록 기능 추가
  src/main/java/beyond/momentours/date_course/command/application/controller/DateCourseController.java
  src/main/java/beyond/momentours/date_course/command/application/dto/DateCourseDTO.java
  src/main/java/beyond/momentours/date_course/command/application/mapper/DateCourseConverter.java
  src/main/java/beyond/momentours/date_course/command/application/service/DateCourseService.java
  src/main/java/beyond/momentours/date_course/command/application/service/DateCourseServiceImpl.java
  src/main/java/beyond/momentours/date_course/command/domain/aggregate/CourseType.java
  src/main/java/beyond/momentours/date_course/command/domain/aggregate/entity/DateCourse.java
  src/main/java/beyond/momentours/date_course/command/domain/repository/DateCourseRepository.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/request/RequestCreateDateCourseVO.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/response/ResponseCreateDateCourseVO.java
  src/main/java/beyond/momentours/date_course/query/repository/DateCourseMapper.java
Labels: feat✨, BackEnd🔙

#50 fix: @AuthenticationPrincipal 를 활용한 CustomUserDetails 클래스 파라미터 추가 및 Reply 삭제
  src/main/java/beyond/momentours/comment/command/application/controller/CommentController.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentService.java
  src/main/java/beyond/momentours/comment/command/application/service/CommentServiceImpl.java
  src/main/java/beyond/momentours/date_course/command/application/service/DateCourseServiceImpl.java
  src/main/java/beyond/momentours/plan/command/application/controller/PlanController.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanService.java
  src/main/java/beyond/momentours/plan/command/application/service/PlanServiceImpl.java
  src/main/java/beyond/momentours/reply/command/application/controller/ReplyController.java
  src/main/java/beyond/momentours/reply/command/application/dto/ReplyDTO.java
  src/main/java/beyond/momentours/reply/command/application/mapper/ReplyConvertor.java
  src/main/java/beyond/momentours/reply/command/application/service/ReplyService.java
  src/main/java/beyond/momentours/reply/command/application/service/ReplyServiceImpl.java
  src/main/java/beyond/momentours/reply/command/domain/aggregate/entity/Reply.java
  src/main/java/beyond/momentours/reply/command/domain/repository/ReplyRepository.java
  src/main/java/beyond/momentours/reply/command/domain/vo/request/RequestCreateReplyVO.java
  src/main/java/beyond/momentours/reply/command/domain/vo/request/RequestUpdateReplyVO.java
  src/main/java/beyond/momentours/reply/command/domain/vo/response/ResponseCreateReplyVO.java
  src/main/java/beyond/momentours/reply/command/domain/vo/response/ResponseUpdateReplyVO.java
  src/main/java/beyond/momentours/reply/query/repository/ReplyMapper.java
  src/main/resources/beyond/momentours/mapper/reply/ReplyMapper.xml
Labels: BackEnd🔙, fix🛠️

#52 feat(#51): 데이트코스 등록 추가
  src/main/java/beyond/momentours/date_course/command/application/controller/DateCourseController.java
  src/main/java/beyond/momentours/date_course/command/application/dto/DateCourseDTO.java
  src/main/java/beyond/momentours/date_course/command/application/service/DateCourseServiceImpl.java
  src/main/java/beyond/momentours/date_course/command/domain/vo/request/RequestCreateDateCourseVO.java
  src/main/java/beyond/momentours/date_course_location/command/application/service/DateCourseLocationService.java
  src/main/java/beyond/momentours/date_course_location/command/application/service/DateCourseLocationServiceImpl.java
  src/main/java/beyond/momentours/date_course_location/command/domain/aggregate/entity/DateCourseLocation.java
  src/main/java/beyond/momentours/date_course_location/command/domain/repository/DateCourseLocationRepository.java
  src/main/java/beyond/momentours/date_course_location/command/domain/vo/DateCourseLocationVO.java
  src/main/java/beyond/momentours/location/command/application/dto/LocationDTO.java
  src/main/java/beyond/momentours/location/command/application/dto/RequestLocationDTO.java
  src/main/java/beyond/momentours/location/command/application/dto/ResponseLocationDTO.java
  src/main/java/beyond/momentours/location/command/application/mapper/LocationConverter.java
  src/main/java/beyond/momentours/location/command/application/service/LocationService.java
  src/main/java/beyond/momentours/location/command/application/service/LocationServiceImpl.java
  src/main/java/beyond/momentours/location/command/domain/aggregate/LocationStatus.java
  src/main/java/beyond/momentours/location/command/domain/aggregate/entity/Location.java
  src/main/java/beyond/momentours/location/query/repository/LocationMapper.java
  src/main/resources/beyond/momentours/mapper/location/LocationMapper.xml
Labels: feat✨, BackEnd🔙, fix🛠️

#53 feat(#46, #47): 회원정보 조회 및 로그인 이력
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/member/command/application/controller/MemberController.java
  src/main/java/beyond/momentours/member/command/application/mapper/MemberConverter.java
  src/main/java/beyond/momentours/member/command/application/service/LoginHistoryService.java
  src/main/java/beyond/momentours/member/command/application/service/LoginHistoryServiceImpl.java
  src/main/java/beyond/momentours/member/command/application/service/MemberService.java
  src/main/java/beyond/momentours/member/command/application/service/MemberServiceImpl.java
  src/main/java/beyond/momentours/member/command/domain/aggregate/entity/LoginHistory.java
  src/main/java/beyond/momentours/member/command/domain/repository/LoginHistoryRepository.java
  src/main/java/beyond/momentours/member/query/controller/MemberController.java
  src/main/java/beyond/momentours/member/query/mapper/MemberQueryConverter.java
  src/main/java/beyond/momentours/member/query/repository/MemberMapper.java
  src/main/java/beyond/momentours/member/query/service/MemberQueryService.java
  src/main/java/beyond/momentours/member/query/service/MemberQueryServiceImpl.java
  src/main/java/beyond/momentours/member/query/vo/response/ResponseMypageVO.java
  src/main/java/beyond/momentours/security/AuthenticationFilter.java
  src/main/java/beyond/momentours/security/SecurityConfig.java
  src/main/resources/beyond/momentours/mapper/member/MemberMapper.xml
Labels: feat✨, BackEnd🔙, fix🛠️

#67 Feat: 공지 조회 , 수정 , 삭제, 등록 기능
  src/main/java/beyond/momentours/announcement/command/application/controller/AnnouncementController.java
  src/main/java/beyond/momentours/announcement/command/application/service/AnnouncementService.java
  src/main/java/beyond/momentours/announcement/command/application/service/AnnouncementServiceImpl.java
  src/main/java/beyond/momentours/announcement/command/domain/aggregate/dto/request/CreateAnnouncementRequestDTO.java
  src/main/java/beyond/momentours/announcement/command/domain/aggregate/dto/request/UpdateAnnouncementRequestDTO.java
  src/main/java/beyond/momentours/announcement/command/domain/aggregate/dto/response/AnnouncementResponseDTO.java
  src/main/java/beyond/momentours/announcement/command/domain/aggregate/entity/Announcement.java
  src/main/java/beyond/momentours/announcement/command/domain/repository/AnnouncementRepository.java
  src/main/java/beyond/momentours/announcement/query/config/MyBatisConfiguration.java
  src/main/java/beyond/momentours/announcement/query/controller/AnnouncementQueryController.java
  src/main/java/beyond/momentours/announcement/query/dto/AnnouncementDTO.java
  src/main/java/beyond/momentours/announcement/query/repository/AnnouncementMapper.java
  src/main/java/beyond/momentours/announcement/query/service/AnnouncementQueryService.java
  src/main/java/beyond/momentours/announcement/query/service/AnnouncementQueryServiceImpl.java
  src/main/java/beyond/momentours/inquiry/command/application/controller/InquiryController.java
  src/main/java/beyond/momentours/inquiry/command/application/service/InquiryCommandService.java
  src/main/java/beyond/momentours/inquiry/command/application/service/InquiryCommandServiceImpl.java
  src/main/java/beyond/momentours/inquiry/command/domain/aggregate/dto/request/InquiryAnswerCreateOrUpdateDTO.java
  src/main/java/beyond/momentours/inquiry/command/domain/aggregate/dto/request/InquiryCreateOrUpdateRequestDTO.java
  src/main/java/beyond/momentours/inquiry/command/domain/aggregate/dto/response/InquiryAnswerResponseDTO.java
  src/main/java/beyond/momentours/inquiry/command/domain/aggregate/dto/response/InquiryResponseDTO.java
  src/main/java/beyond/momentours/inquiry/command/domain/aggregate/entity/Inquiry.java
  src/main/java/beyond/momentours/inquiry/command/domain/aggregate/entity/InquiryAnswer.java
  src/main/java/beyond/momentours/inquiry/command/domain/repository/InquiryRepository.java
  src/main/java/beyond/momentours/inquiry/query/controller/InquiryQueryController.java
  src/main/java/beyond/momentours/inquiry/query/dto/InquiryAndInquiryAnswerDTO.java
  src/main/java/beyond/momentours/inquiry/query/dto/InquiryAnswerDTO.java
  src/main/java/beyond/momentours/inquiry/query/dto/InquiryDTO.java
  src/main/java/beyond/momentours/inquiry/query/repository/InquiryMapper.java
  src/main/java/beyond/momentours/inquiry/query/service/InquiryQueryService.java
  src/main/java/beyond/momentours/inquiry/query/service/InquiryQueryServiceImpl.java
  src/main/resources/beyond/momentours/mapper/Inquiry/InquiryMapper.xml
  src/main/resources/beyond/momentours/mapper/announcement/AnnouncementMapper.xml
  src/test/java/beyond/momentours/announcement/command/application/service/AnnouncementServiceImplTest.java
Labels: feat✨, BackEnd🔙

#72 feat( #71 ): 데이트 코스 즐겨찾기 생성, 삭제, 조회 기능 추가
  src/main/java/beyond/momentours/common/exception/ErrorCode.java
  src/main/java/beyond/momentours/config/RedisConfig.java
  src/main/java/beyond/momentours/config/SchedulerConfig.java
  src/main/java/beyond/momentours/course_scrap/command/domain/aggregate/entity/CourseScrap.java
  src/main/java/beyond/momentours/course_scrap_folder/command/application/controller/CourseScrapFolderController.java
  src/main/java/beyond/momentours/course_scrap_folder/command/application/dto/CourseScrapFolderDTO.java
  src/main/java/beyond/momentours/course_scrap_folder/command/application/mapper/CourseScrapFolderConverter.java
  src/main/java/beyond/momentours/course_scrap_folder/command/application/service/CourseScrapFolderService.java
  src/main/java/beyond/momentours/course_scrap_folder/command/application/service/CourseScrapFolderServiceImpl.java
  src/main/java/beyond/momentours/course_scrap_folder/command/domain/aggregate/entity/CourseScrapFolder.java
  src/main/java/beyond/momentours/course_scrap_folder/command/domain/repository/CourseScrapFolderRepository.java
  src/main/java/beyond/momentours/course_scrap_folder/command/domain/vo/request/RequestCreateCourseScrapFolderVO.java
  src/main/java/beyond/momentours/course_scrap_folder/command/domain/vo/response/ResponseCourseScrapFolderVO.java
  src/main/java/beyond/momentours/course_scrap_folder/command/domain/vo/response/ResponseCreateCourseScrapFolderVO.java
  src/main/java/beyond/momentours/course_scrap_folder/query/repository/CourseScrapFolderMapper.java
  src/main/java/beyond/momentours/date_course/command/domain/aggregate/entity/DateCourse.java
  src/main/resources/beyond/momentours/mapper/course_scrap_folder/CourseScrapFolderMapper.xml
Labels: feat✨, BackEnd🔙

#74 Refactor: 추억 등록 구조 대거 수정
  src/main/java/beyond/momentours/location/command/domain/aggregate/entity/Location.java
  src/main/java/beyond/momentours/moment/command/application/controller/MomentController.java
  src/main/java/beyond/momentours/moment/command/application/dto/ResponseMomentDTO.java
  src/main/java/beyond/momentours/moment/command/application/mapper/MomentConverter.java
  src/main/java/beyond/momentours/moment/command/application/service/MomentService.java
  src/main/java/beyond/momentours/moment/command/application/service/MomentServiceImpl.java
  src/main/java/beyond/momentours/moment/command/domain/aggregate/entity/Moment.java
  src/test/java/beyond/momentours/moment/command/application/service/MomentServiceImplTests.java
Labels: feat✨, refactor✂️
